### ISSUE TITLE
Add waypoints column to cargo movements df

### ISSUE THREAD

**Issue by syed1992** [VorTECHsa/python-sdk#117]
Would be really useful to have a a waypoints column to identify which waypoints a vessel has passed through on a voyage. Imagine this would be numbered in the same way as multiple sts events can be numbered.

Having this would also allow us to create some insight reports and snapshot pieces publicising the feature.

**Comment by KitBurgess** [comment]
You can currently filter cargo movements on waypoints: Ie _"Show me all the cargo movements that passed through the Suez Canal on these dates.."_. The API doesn't currently return the cargo movement waypoints though, so the SDK doesn't currently have the ability to show these.

**Comment by KitBurgess** [comment]
What insight report / snapshot piece would you be looking to create? - Would the filter on waypoints functionality be sufficient?

**Comment by KitBurgess** [comment]
Closing this as this is an API piece, not SDK
