### ISSUE TITLE
Update requests package to prevent security issue

### ISSUE THREAD

**Issue by ksoekarjo-shell** [VorTECHsa/python-sdk#342]
**Is your feature request related to a problem? Please describe.**
The python-sdk currently requires requests 2.22.0, which depends on urllib3 <1.26. urllib3 <1.26.5 contains a severe vulnerability: https://github.com/advisories/GHSA-q2q7-5pp4-w6pg

**Describe the solution you'd like**
Upgrade the requests package to the latest version. This supports urllib3 ^1.26.5, solving the security issue. Pull request already exists: https://github.com/VorTECHsa/python-sdk/pull/333

**Comment by kahoowkh** [comment]
resolved in version [0.34.1](https://github.com/VorTECHsa/python-sdk/releases/tag/)
