### ISSUE TITLE
Old branches

### ISSUE THREAD

**Issue by VRGhost** [VorTECHsa/python-sdk#399]
Hello,

I have identified the following inactive (no commit in the last 30 days) branches:
|  Branch Name  |  Last commit age (days) | Last commit message | Comitter |
|---------------|-------------------------|---------------------|----------|
| jupyter_notebook_introduction | 1073 | updated notebook | natday |
| fix-46 | 1068 | added flattening logic to Result base class, also moved multiproc call to utils | cvonsteg |
| levels | 1008 | feat: Start to explore presenting a cargo movement across multiple levels | Christopher Burgess |
| breakdown | 967 | feat: Start to add the breakdown endpoint | Christopher Burgess |
| webinar21apr | 941 | docs: Add webinar examples | Christopher Burgess |
| fix/vessel_status | 918 | fix: test vessel_status as array | asfakianakis |
| no-parallel-conversion | 856 | Merge branch 'better-logging' into no-parallel-conversion | christoper burgess |
| custom-theme | 822 | style: Try changing colour | christoper burgess |
| fix-setup-apikey | 813 | fix: set all_test_pass to False if API KEY not found | cvonsteg |
| feat-add-speed-endpoint | 744 | chore: wip | dufia |
| ci-automation | 687 | chore: Try this out with the new branch protection rules | Kit Burgess |
| docs-interactive | 683 | chore: Jupyter sits in test, not core requirement | Kit Burgess |
| autogenerate-config-docs | 682 | chore: Store this here for now, TODO | Kit Burgess |
| test-if-works | 540 | ci: Does ci work | Kit Burgess |
| chore-effective-controller | 428 | chore: rename to controller | Pawel |
| feat-enhance-deps | 399 | fix: deps | Radu Ghitescu |
| fix-unify-unit-defaults | 367 | chore: fix comment | valeriiashmyhlo |
| perf-improvements | 184 | fix(cargo-mvmts-sdk): explore potential perf improvements | Hilary Kitz |
| chore-fake-branch | 91 | chore: another comma | Pawel Pietruszka |
| feat-cargo-timeseries-property | 53 | fix: to_df on TimeSeriesResult correctly creates additional columns | Huan Min Gan |
| dependabot/pip/flake8-5.0.4 | 51 | chore(deps-dev): bump flake8 from 3.7.9 to 5.0.4 <br>  <br> Bumps [flake8](https://github.com/pycqa/flake8) from 3.7.9 to 5.0.4. <br> - [Release notes](https://github.com/pycqa/flake8/releases) <br> - [Commits](https://github.com/pycqa/flake8/compare/3.7.9...5.0.4) <br>  <br> --- <br> updated-dependencies: <br> - dependency-name: flake8 <br>   dependency-type: direct:development <br>   update-type: version-update:semver-major <br> ... <br>  <br> Signed-off-by: dependabot[bot] <support@github.com> | GitHub |
| dependabot/pip/pyyaml-lt-7.0.0 | 51 | chore(deps-dev): update pyyaml requirement from <6.0.0 to <7.0.0 <br>  <br> Updates the requirements on [pyyaml](https://github.com/yaml/pyyaml) to permit the latest version. <br> - [Release notes](https://github.com/yaml/pyyaml/releases) <br> - [Changelog](https://github.com/yaml/pyyaml/blob/master/CHANGES) <br> - [Commits](https://github.com/yaml/pyyaml/compare/3.01...6.0) <br>  <br> --- <br> updated-dependencies: <br> - dependency-name: pyyaml <br>   dependency-type: direct:development <br> ... <br>  <br> Signed-off-by: dependabot[bot] <support@github.com> | GitHub |
| dependabot/pip/tabulate-0.9.0 | 42 | chore(deps-dev): bump tabulate from 0.8.7 to 0.9.0 <br>  <br> Bumps [tabulate](https://github.com/astanin/python-tabulate) from 0.8.7 to 0.9.0. <br> - [Release notes](https://github.com/astanin/python-tabulate/releases) <br> - [Changelog](https://github.com/astanin/python-tabulate/blob/master/CHANGELOG) <br> - [Commits](https://github.com/astanin/python-tabulate/compare/v0.8.7...v0.9.0) <br>  <br> --- <br> updated-dependencies: <br> - dependency-name: tabulate <br>   dependency-type: direct:development <br>   update-type: version-update:semver-minor <br> ... <br>  <br> Signed-off-by: dependabot[bot] <support@github.com> | GitHub |.

You can run this command in the local checkout of the repo:
```bash

git push origin --delete jupyter_notebook_introduction fix-46 levels breakdown webinar21apr fix/vessel_status no-parallel-conversion custom-theme fix-setup-apikey feat-add-speed-endpoint ci-automation docs-interactive autogenerate-config-docs test-if-works chore-effective-controller feat-enhance-deps fix-unify-unit-defaults perf-improvements chore-fake-branch feat-cargo-timeseries-property dependabot/pip/flake8-5.0.4 dependabot/pip/pyyaml-lt-7.0.0 dependabot/pip/tabulate-0.9.0

```
If you would like to remove them.

**Comment by SeanBarry** [comment]
Branches have been tidied up.
