### ISSUE TITLE
TimeSeriesResult.to_df() breaking after the latest changes in case the records are empty

### ISSUE THREAD

**Issue by ersanjeev007** [VorTECHsa/python-sdk#499]
**KeyError in to_df() method of TimeSeriesResult**
When we call to_df('all') of TimeSeriesResult and records are empty, then it gives KeyError. 

**To Reproduce**
Code to reproduce the behavior:

`df = VesselAvailabilityTimeseries().search(**params).to_df('all')
`

and the records are empty, then it raises the below execption.

![image](https://github.com/VorTECHsa/python-sdk/assets/30767578/995ab70e-d4b3-4142-b669-52f8c2fc7466)

**Expected behavior**
to_df() should be able to handle the cases when records are empty, as it use to work before.

**Reproduced in version**
__version__ = "0.72.3"

**Comment by ministrudels** [comment]
Hi @ersanjeev007. Thank you for raising. This has since been resolved in https://github.com/VorTECHsa/python-sdk/pull/500. Please upgrade your sdk version to 0.72.4
