### ISSUE TITLE
Add pydantic 2.x

### ISSUE THREAD

**Issue by thomasfrederikhoeck** [VorTECHsa/python-sdk#514]
**Is your feature request related to a problem? Please describe.**
Currently this package only allows `pydantic<2`. This create dependency conflict since many other packages now use pydantic 2.x which was released in June 2023.

**Describe the solution you'd like**
Allow pydantic 2.x and make code changes if needed.

**Comment by SeanBarry** [comment]
Hey, sorry for the delayed response. I'm working on a release that upgrades a lot of packages including Pydantic. I'll hopefully have it ready to test imminently. I will release it as a pre-release and post here so you can test it and give any feedback.
Thanks

**Comment by thomasfrederikhoeck** [comment]
@SeanBarry Is it also possible to loosen the requirement for `tqdm`? Maybe just `tqdm<5.0.0` if you are affraid of breaking changes.

**Comment by SeanBarry** [comment]
@thomasfrederikhoeck, Yes I've done that too. There is pre-release version ready for testing. One requirement to install it is that you need to be using Python 3.11
Are you able to give it a shot and pass me back any feedback? I'm keen to make sure you aren't blocked and I'm happy to help you get up and running.

Pre-release version `1.0.0a4` here: https://pypi.org/project/vortexasdk/1.0.0a4/

**Comment by thomasfrederikhoeck** [comment]
@SeanBarry Yes, we will try and take it for a spin

**Comment by oofaish** [comment]
Thanks for this but sadly I am still in 3.9. Any context I. What created the 3.11 requirement? Thank you

**Comment by SeanBarry** [comment]
Hey @oofaish, it was using 3.7 which is now at **end-of-life**. 3.9 has less than a year left before it too will be **end-of-life**. 3.11 is halfway through its lifecycle and is now over 2 years old, so it seemed like an appropriate version to upgrade to.

I assume you're working in an environment where upgrading language versions is not trivial? If so, I can try downgrading to 3.9 and seeing what breaks.

**Comment by SeanBarry** [comment]
Hey @oofaish, I've downgraded the required Python version from 3.11 to 3.9. There is a pre-release ready for you to try out.
`pip install vortexasdk==1.0.1a1`
Please give it a try, and let me know if there are any issues. @thomasfrederikhoeck if you wish to give this version a try too, please do.
Please let me know how you both get on, and if successful - I can create a full release!

**Comment by thomasfrederikhoeck** [comment]
@SeanBarry  I can confirm the `1.0.0a4` works for us. Thank you! :-)

**Comment by oofaish** [comment]
I all aim to try today - thanks!

**Comment by oofaish** [comment]
@SeanBarry could we relax the pandas dependency or is that a requirement too? Sorry I am dealing with a legacy codebase - appreciate all the help - seem to be dealing with 1.4'ish still - although hoping to update at some point ....

**Comment by SeanBarry** [comment]
Hey @thomasfrederikhoeck, glad to hear it works. Please tag me directly in any issues in the future just to make sure you get a swift response. 

@oofaish, I will experiment with Pandas 1.4 and get back to you next week. I've created a new issue for that [here](https://github.com/VorTECHsa/python-sdk/issues/529).

Changes for this ticket were fixed by https://github.com/VorTECHsa/python-sdk/pull/526
