### ISSUE TITLE
Create sample notebook with charts

### ISSUE THREAD

**Issue by Natday** [VorTECHsa/python-sdk#72]
It would be great if we had a notebook similar to [this](https://github.com/Pierian-Data/Complete-Python-3-Bootcamp/blob/master/05-Object%20Oriented%20Programming/01-Object%20Oriented%20Programming.ipynb). 

This notebook could walk someone through how to connect to our API, and also show some of the potential uses of the data

**Comment by KitBurgess** [comment]
Thanks for the feedback - could you expand on which aspects are difficult to get started with as a beginner?

Also, could you describe where https://v0rt3x4.github.io/python-sdk/endpoints/geographies/ falls down / why it isn't useful etc. It currently gives an example of how to connect to the API?

**Comment by Natday** [comment]
I didn't know how to set an environment variable, some links in the documentation would have been useful. 

The current documentation is quite extensive, but seems more geared towards advanced users.

This may be personal preference, but when I am learning how to use something I prefer to look at lots of examples. Then tweak the examples to what I would like to see, and as I get more confident I will start to make my own queries/ API calls.

By providing a Jupyter Notebook with a bunch of API calls and what you can do with this data, I believe this will make the product more accessible, and more attractive to prospective users

**Comment by KitBurgess** [comment]
@all-contributors add @Natday for business, idea, userTesting
